### PR TITLE
Merge "feature/Andy_updates_202109" into "support/HAFS"

### PR DESCRIPTION
**Pull request by ghassan-alaka**
This PR is to integrate updates that @AndrewHazelton had made to his local _support/HAFS_ branch.

### CODE REVIEW

**Review by ghassan-alaka — COMMENTED** [review]
These changes all look good to me. @AndrewHazelton should double-check the master namelist to ensure accuracy of all settings.

**Comment by ghassan-alaka** [comment]
@AndrewHazelton should these changes also be merged into the non-workflow version of GPLOT?

**Comment by AndrewHazelton** [comment]
Yes these should be moved in there I think.

**Review by AndrewHazelton — APPROVED** [review]
Looks good.

**Pull request merged**
