### PR TITLE
Merge 'realtime2022' into 'develop'

### PR DESCRIPTION
**Pull request by ghassan-alaka**
## Description of changes
This PR will merge all commits that were made before and during the 2022 HFIP Real-Time Experiments. The realtime2022 branch contains critical organizational updates as well, including a modified directory structure. A key upgrade is the unification of workflow and independent running modes, which are now easily controlled by a namelist option (see Issue #25 below). Another key upgrade is the addition of two new graphical modules, airsea and ocean_maps (developed by @lgramer); note a prior dependency on repository 'fix' files has been removed in these modules. Modules and software were all updated across RDHPCS platforms. This PR contains numerous small fixes and updates that can be evaluated in greater detail.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes [https://github.com/ghassan-alaka/GPLOT/issues/25](https://github.com/ghassan-alaka/GPLOT/issues/25)
- fixes [https://github.com/ghassan-alaka/GPLOT/issues/27](https://github.com/ghassan-alaka/GPLOT/issues/27)

## Contributors (optional)
@AndrewHazelton 
@lgramer 
@mlaurako 

## Tests conducted
The 'realtime2022' branch has been extensively tested on all RDHPCS machines (i.e., Jet, Hera, Orion). It has been deployed in workflow and independent modes with equal success. It features two new modules. What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests. What platform(s) were used for testing?

- [x] Jet
- [x] Hera
- [x] Orion
- [ ] WCOSS2

### CODE REVIEW

**Comment by ghassan-alaka** [comment]
@AndrewHazelton @lgramer I initiated this PR, but I'm not in a rush to merge it just yet. I think our testing of the 'realtime2022' branch has gone very well. Thank you for assisting with the tests in "workflow" running mode. It has been getting the job done in "independent" running mode (e.g., for GFS) as well. This means we are almost ready to merge everything back into the 'develop' and, ultimately, the 'master' branch. This will allow me to tag a new version and it will allow for cleaner developments going forward. My next target is to update the Python environment to use the one maintained by EMC's Maria Aristizabal, which should mimick the environment available on WCOSS2.

Anyway, updates/questions/concerns are welcome!

**Review by AndrewHazelton — APPROVED** [review]
Looks good!

**Comment by AndrewHazelton** [comment]
> Targeting the WCOSS2 Python environment is a good idea. Gotta make sure it has metpy and some of the other features needed for the polar module to run successfully.

**Review by lgramer — APPROVED** [review]
Merges multiple improvements and fixes, including new air-sea relevant atmospheric maps and ocean output file-based maps. Extensively tested both within HAFS workflow and as a stand-alone graphical tool. Necessary update in preparation to convert to full (NCO-compliant) python transition.

**Pull request merged**
